name: Deploy to Atatus

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Call External API Action
        uses: ./
        with:
          api_key: ${{ secrets.ATATUS_API_KEY }}
          changes: ${{ env.CHANGED_FILES }}
          revision: ${{ github.run_number }}
          release_stage: 'production'
          project_id: ${{ secrets.ATATUS_PROJECT_ID }}



